name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-lsujeonggithub-project-name-test-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - run: echo "Hello World 222!"
